sudo : required

services:
    - Docker

before_install :
    - docker build -t rgouthaman/docker-react -f Dockerfile.dev .

script:
    - docker run rgouthaman/docker-react npm run test -- --coverage