version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /CICD/node_modules
            - .:/CICD
    test:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        command: ["npm","run","test"]
